Refactor error handling and properly use server actions
saleor/adyen-app-testclient pull request #16
Opened 2024-08-27 10:45 UTC by krzysztofzuraw

- **Migrate env**
- **Migrate checkout details**
- **Migrate gateway**
- **migrate dropin**
- **migrate summary**
- **Remove leftovers**
- **Add cache**

2024-08-28 13:03 UTC, witoszekdev requested changes

2024-08-29 07:07 UTC, lkostrowski commented on src/modules/environment/components/environment.tsx
> +    }
I think we can rethink this when we implement e2e tests.

2024-08-29 07:07 UTC, lkostrowski approved these changes

2024-08-29 07:14 UTC, krzysztofzuraw commented on src/modules/checkout-details/actions/update-shipping-address.ts
> +        name: "ParsingUpdateShippingAddressError",
I've added myself a task for that 😄

2024-08-29 07:15 UTC, krzysztofzuraw commented on src/modules/dropin/schemas/initalize-transaction.ts
> +        resultCode: z.enum(["Authorised", "Pending", "Refused", "Received"]),
It will be added in next PR when I integrate Givex payments

2024-08-29 07:15 UTC, krzysztofzuraw commented on src/modules/dropin/schemas/initalize-transaction.ts
> +    data: z.object({
I added passthrough in Givex payment PR 😄

2024-08-29 07:16 UTC, krzysztofzuraw commented on src/modules/dropin/schemas/transaction-process.ts
> +        resultCode: z.enum(["Authorised", "Pending", "Refused", "Received"]),
It will be added in next PR when I integrate Givex payments

2024-08-29 07:16 UTC, krzysztofzuraw commented on src/modules/dropin/schemas/transaction-process.ts
> +    data: z.object({
I will create a task for that - this PR already has 700 lines of changes 😄

2024-08-29 10:00 UTC, witoszekdev approved these changes

2024-08-29 10:06 UTC, merged